### ISSUE TITLE
UnboundLocalError: cannot access local variable 'message_text' where it is not associated with a value

### ISSUE THREAD

**Issue by JakobLichterfeld** [JakobLichterfeld/TeslaMate-Telegram-Bot#34]
v0.7.3 runs on test system, fails on production with:

> teslamatetelegrambot  | Traceback (most recent call last):
> teslamatetelegrambot  |   File "/app/./src/teslamate_telegram_bot.py", line 227, in <module>
> teslamatetelegrambot  |     asyncio.run(main())
> teslamatetelegrambot  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
> teslamatetelegrambot  |     return runner.run(main)
> teslamatetelegrambot  |            ^^^^^^^^^^^^^^^^
> teslamatetelegrambot  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
> teslamatetelegrambot  |     return self._loop.run_until_complete(task)
> teslamatetelegrambot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> teslamatetelegrambot  |   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
> teslamatetelegrambot  |     return future.result()
> teslamatetelegrambot  |            ^^^^^^^^^^^^^^^
> teslamatetelegrambot  |   File "/app/./src/teslamate_telegram_bot.py", line 205, in main
> teslamatetelegrambot  |     await check_state_and_send_messages(bot, chat_id)
> teslamatetelegrambot  |   File "/app/./src/teslamate_telegram_bot.py", line 172, in check_state_and_send_messages
> teslamatetelegrambot  |     await send_telegram_message_to_chat_id(bot, chat_id, message_text)
> teslamatetelegrambot  |                                                          ^^^^^^^^^^^^
> teslamatetelegrambot  | UnboundLocalError: cannot access local variable 'message_text' where it is not associated with a value
> teslamatetelegrambot exited with code 0

**Comment by JakobLichterfeld** [comment]
solved by https://github.com/JakobLichterfeld/TeslaMate-Telegram-Bot/commit/5d6267fc952a496417663f741e8cdbccfdee64b7
